### ISSUE TITLE
Pydio Cells is not compatible with modern Reverse Proxys

### ISSUE THREAD

**Issue by Berndinox** [pydio/cells#19]
I've played around a while, but it seems like pydio is not able to be accessible behind traefik reverse proxy and ssl offloading.

```
Opening URL http://cloud.berndklaus.at:8080 in your browser. Please copy/paste it if the browser is not on the same machine.
2018-09-11T22:02:11.204Z        INFO    [INFO] cloud.berndklaus.at - No such site at :8080 (Remote: 10.0.0.115, Referer: )
```
I've used all possible combinations of the CELLS_BIND and CELLS_EXTERNAL Env Vars. Nothing did work.
Traefik is basicly offloading ssl, it also redirects http to https.
All other services work pretty well.

Finally this solution worked so that i can connect through the proxy

```
      image: pydio/cells:latest
      restart: always
      volumes: ["static:/root/.config/pydio/cells/static/pydio", "data:/root/.config/pydio/cells/data"]
      environment:
        - CELLS_BIND=cloud.berndklaus.at:8080
        #- CELLS_EXTERNAL=cloud.berndklaus.at:8080
        - CELLS_NO_SSL=1
      networks:
        proxy:
          aliases:
            - cells
        default:
      deploy:
        replicas: 1
        labels:
          - "traefik.port=8080"
          - "traefik.docker.network=proxy"
          - "traefik.frontend.rule=Host:cloud.berndklaus.at"
          - "traefik.backend=cells"
          - "traefik.frontend.entryPoints=http,https"
```

But then the install failes:

`2018-09-11T21:54:55.354Z        ERROR   pydio.grpc.gateway.proxy        Could not run   {"error": "cannot create storage without CA URL"}`

Setup is contiuing but i just receive "Bad Gateway" after..
The Documentation is not really saying alot about this...

**Comment by ghecquet** [comment]
Hi there,

Can you please use the forum in the future to ask for help on a setup issue 
 ? (https://github.com/pydio/cells/blob/master/CONTRIBUTING.md)

That being said, you should try removing the CELLS_NO_SSL (and re-adding the CELLS_EXTERNAL config). This will start the pydio cells with ssl self_signed. Communication between your proxy and cells should then be using ssl, so redirect to https instead of http.

The way the CELLS_EXTERNAL currently work is that you can't have a different domain / protocol than what is setup in the proxy at the moment. That is a shortcoming we've been recently been made aware of and we'll add that to the documentation shortly.

Thanks,
Greg

**Comment by Berndinox** [comment]
HY @ghecquet - **thanks** for the quick response, from my pov this was an issue. You may add a quick notice to the Documentation so Users got not confused (like me) :)

**Comment by ghecquet** [comment]
Hi, can you please give any more details on your configuration to see if we can help you out ?

Thanks,
Greg

**Comment by gardart** [comment]
Sure, I'm going to do a fresh install and I will post the output here later this week
Thanks

**Comment by ston3o** [comment]
This configuration works : 

```yml
# pydio.yml

version: '3'

services:
  pydio:
    image: pydio/cells:1.2.1
    volumes: ["data:/root/.config/pydio/cells:nocopy"]
    environment:
      - CELLS_BIND=0.0.0.0:8080
      - CELLS_EXTERNAL=${DOMAIN:?err}
      - CELLS_NO_SSL=1
    deploy:
      labels:
        traefik.port: 8080
        traefik.frontend.rule: Host:${DOMAIN:?err}
        traefik.enable: "true"
        traefik.docker.network: traefik-net
    networks:
      - internal
      - traefik

  mysql:
    image: mysql:5.7
    volumes: ["mysql:/var/lib/mysql:nocopy"]
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: cells
      MYSQL_USER: pydio
      MYSQL_PASSWORD: P@ssw0rd
    networks:
      - internal

volumes:
  data:
  mysql:

networks:
  internal:
  traefik:
    external:
      name: traefik-net
```

After deploy with `DOMAIN=mydomain.com docker stack deploy -c pydio.yml pydio`, I changed manually the `/root/.config/pydio/cells/pydio.json` file with the good `url` param : 

"url": "http://mydomain.com" -> "url": "https://mydomain.com"

Thanks to [@bschulz87](https://gist.github.com/bschulz87/fc1f6968ea97b1c034bfa4811b35e17d)

**Comment by Mohl** [comment]
I stuck quite some time on this - you HAVE to add a port to the CELLS_BIND value.

Here are my envs for Pydio with letsencrypt:

`
CELLS_NO_SSL | 0
CELLS_EXTERNAL | pydio.my.domain
PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
CELLS_VERSION | 1.2.1
VIRTUAL_HOST | pydio.my.domain
LETSENCRYPT_HOST | pydio.my.domain
LETSENCRYPT_EMAIL | myemail@mydomain.com
VIRTUAL_PORT | 8080
CELLS_BIND | pydio.my.domain:8080 //<- This port is MANDATORY!
`

**Comment by cdujeu** [comment]
Thx @Mohl indeed we have updated the docs for that. Closing this for now.

**Comment by thepenguinthatwants** [comment]
Hi!

Sorry for bumping closed issue.

I tried to get this work on locally. But getting weird sql issues. Has this image being changed or something?

I tried to make it work locally.

```
version: '3'

services:
  pydio:
    image: pydio/cells:1.2.1
    volumes: ["data:/root/.config/pydio/cells:nocopy"]
    environment:
      - CELLS_BIND=0.0.0.0:8080
      - CELLS_EXTERNAL=pydio.localhost 
      # - CELLS_NO_SSL=1
    labels:
        traefik.port: 8080
        traefik.frontend.rule: Host:pydio.localhost
        traefik.enable: "true"
        traefik.docker.network: srv
    networks:
      - internal
      - srv

  mysql:
    image: mysql:5.7
    volumes: ["mysql:/var/lib/mysql:nocopy"]
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: cells
      MYSQL_USER: pydio
      MYSQL_PASSWORD: P@ssw0rd
    networks:
      - internal

volumes:
  data:
  mysql:

networks:
  internal:
  srv:
    external: true
```

Logs says

```
mysql_1  | 2019-07-04T19:08:49.566727Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
mysql_1  | 2019-07-04T19:08:49.589832Z 0 [Note] Event Scheduler: Loaded 0 events
mysql_1  | 2019-07-04T19:08:49.589991Z 0 [Note] mysqld: ready for connections.
mysql_1  | Version: '5.7.26'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
pydio_1  | 2019-07-04T19:08:49.857Z     INFO    Cannot find default database! Please make sure that databases are correctly configured and started.
lufi_pydio_1 exited with code 
```
