### ISSUE TITLE
Unable to restart in docker after ctrl-c shutdown

### ISSUE THREAD

**Issue by xumix** [pydio/cells#241]
I'm unable to get cell up and running after container shutdown and restart.

The steps:

0) Host system is debian 10.1
1) `docker-compose up`
2) Containers start (mariadb takes some time)
3) Do install wizard
4) All seems fine, do some work
4) Ctrl+c in docker-compose shell and wait for graceful shutdown
5) `docker-compose up`

Cell wont start after that, it fails with some errors about storage

```
cells_1  | 2020-06-03T19:57:48.954Z     INFO    pydio.grpc.update       started
cells_1  | 2020-06-03T19:57:48.969Z     INFO    pydio.grpc.data.sync    started
cells_1  | 2020-06-03T19:57:48.969Z     INFO    pydio.grpc.data.sync    Starting umbrella service pydio.grpc.data.sync. with sources    {"sources": ["pydiods1", "personal", "cellsdata"]}
cells_1  | 2020-06-03T19:57:48.969Z     INFO    pydio.grpc.data.sync    Ignoring pydio.grpc.data.sync.pydiods1 as PeerAddress (1a931eabfbdc) does not correspond to any current peer ip
cells_1  | 2020-06-03T19:57:48.969Z     INFO    pydio.grpc.data.sync    Ignoring pydio.grpc.data.sync.personal as PeerAddress (1a931eabfbdc) does not correspond to any current peer ip
cells_1  | 2020-06-03T19:57:48.970Z     INFO    pydio.grpc.data.sync    Ignoring pydio.grpc.data.sync.cellsdata as PeerAddress (1a931eabfbdc) does not correspond to any current peer ip
cells_1  | 2020-06-03T19:57:48.971Z     INFO    pydio.grpc.data.objects started
cells_1  | 2020-06-03T19:57:48.971Z     INFO    pydio.grpc.data.objects Starting umbrella service pydio.grpc.data.objects. with sources {"sources": ["local1"]}
cells_1  | 2020-06-03T19:57:48.972Z     INFO    pydio.grpc.data.objects Ignoring pydio.grpc.data.objects.local1 as PeerAddress (1a931eabfbdc) does not correspond to any current peer ip
cells_1  | 2020-06-03T19:57:48.973Z     ERROR   pydio.web.auth  Could not prepare start         {"error": "Storage is not available"}
cells_1  | 2020-06-03T19:57:48.974Z     ERROR   pydio.grpc.auth Could not prepare start         {"error": "Storage is not available"}
cells_1  | 2020-06-03T19:57:48.975Z     INFO    pydio.gateway.rest      started
cells_1  | 2020-06-03T19:57:48.995Z     INFO    pydio.web.statics       started
cells_1  | 2020-06-03T19:57:48.998Z     INFO    pydio.grpc.log  started
cells_1  | 2020-06-03T19:57:49.000Z     ERROR   pydio.grpc.acl  Could not prepare start         {"error": "Storage is not available"}
cells_1  | 2020-06-03T19:57:49.010Z     ERROR   pydio.grpc.data-key     Could not prepare start         {"error": "Storage is not available"}
cells_1  | 2020-06-03T19:57:49.011Z     INFO    pydio.grpc.docstore     started
cells_1  | 2020-06-03T19:57:49.012Z     ERROR   pydio.grpc.config       Could not prepare start         {"error": "Storage is not available"}
cells_1  | 2020-06-03T19:57:49.012Z     ERROR   pydio.web.oauth Could not prepare start         {"error": "Storage is not available"}
cells_1  | 2020-06-03T19:57:49.013Z     ERROR   pydio.grpc.workspace    Could not prepare start         {"error": "Storage is not available"}
cells_1  | 2020-06-03T19:57:49.013Z     ERROR   pydio.grpc.user-key     Could not prepare start         {"error": "Storage is not available"}
cells_1  | 2020-06-03T19:57:49.014Z     ERROR   pydio.grpc.role Could not prepare start         {"error": "Storage is not available"}
cells_1  | 2020-06-03T19:57:49.014Z     ERROR   pydio.grpc.user-meta    Could not prepare start         {"error": "Storage is not available"}
cells_1  | 2020-06-03T19:57:49.015Z     ERROR   pydio.grpc.policy       Could not prepare start         {"error": "Storage is not available"}
cells_1  | 2020-06-03T19:57:49.015Z     ERROR   pydio.grpc.user Could not prepare start         {"error": "Storage is not available"}
cells_1  | 2020-06-03T19:57:49.015Z     ERROR   pydio.grpc.meta Could not prepare start         {"error": "Storage is not available"}
cells_1  | 2020-06-03T19:57:49.016Z     ERROR   pydio.grpc.oauth        Could not prepare start         {"error": "Storage is not available"}
cells_1  | Activating privacy features... done.
cells_1  | https://192.168.88.217:8080
cells_1  | 2020-06-03T19:57:50.505Z     INFO    pydio.gateway.proxy     started
cells_1  | 2020-06-03T19:57:51.063Z     INFO    pydio.grpc.mailer       Starting mailer with queue 'boltdb'
cells_1  | 2020-06-03T19:57:51.143Z     INFO    pydio.grpc.mailer       Starting mailer with sender 'smtp'
cells_1  | 2020-06-03T19:57:51.170Z     INFO    pydio.grpc.tasks        started
cells_1  | 2020-06-03T19:57:51.202Z     INFO    pydio.grpc.mailer       started
cells_1  | 2020-06-03T19:57:53.056Z     INFO    pydio.grpc.timer        Registering Job {"job": "actions.auth.prune.tokens"}
cells_1  | 2020-06-03T19:57:53.057Z     INFO    pydio.grpc.timer        Registering Job {"job": "flush-mailer-queue"}
cells_1  | 2020-06-03T19:57:53.057Z     INFO    pydio.grpc.timer        Registering Job {"job": "internal-prune-jobs"}
cells_1  | 2020-06-03T19:57:53.057Z     INFO    pydio.grpc.timer        Registering Job {"job": "prune-versions-job"}
cells_1  | 2020-06-03T19:57:53.057Z     INFO    pydio.grpc.timer        Registering Job {"job": "users-activity-digest"}
cells_1  | 2020-06-03T19:57:53.058Z     INFO    pydio.grpc.timer        started
cells_1  | 2020-06-03T19:57:59.193Z     INFO    pydio.gateway.websocket started
cells_1  | 2020-06-03T19:58:00.888Z     ERROR   Error while applying modifiers to registry!     {"error": "{\"id\":\"go.micro.client\",\"code\":500,\"detail\":\"none available\",\"status\":\"Internal Server Error\"}"}
cells_1  | 2020-06-03T19:58:00.992Z     ERROR   Frontend Service Not Detected
cells_1  | 2020-06-03T19:58:05.168Z     ERROR   Error while applying modifiers to registry!     {"error": "{\"id\":\"go.micro.client\",\"code\":500,\"detail\":\"none available\",\"status\":\"Internal Server Error\"}"}
cells_1  | 2020-06-03T19:58:05.272Z     ERROR   Frontend Service Not Detected
cells_1  | 2020-06-03T19:58:09.442Z     ERROR   Error while applying modifiers to registry!     {"error": "{\"id\":\"go.micro.client\",\"code\":500,\"detail\":\"none available\",\"status\":\"Internal Server Error\"}"}
cells_1  | 2020-06-03T19:58:09.546Z     ERROR   Frontend Service Not Detected
cells_1  | 2020-06-03T19:58:10.701Z     INFO    pydio.gateway.proxy     Restarting proxy        {"caddyfile": "\nhttps://192.168.88.217:8080 {\n\tproxy /a  172.24.0.3:44595 {\n\t\twithout /a\n\t\theader_upstream Host {host}\n\t\theader_upstream X-Real-IP {remote}\n\t\theader_upstream X-Forwarded-Proto {scheme}\n\t}\n\tproxy /auth/dex PENDING {\n\t\tinsecure_skip_verify\n\t\theader_upstream Host {host}\n\t\theader_upstream X-Real-IP {remote}\n\t\theader_upstream X-Forwarded-Proto {scheme}\n\t}\n\tproxy /oidc PENDING {\n\t\tinsecure_skip_verify\n\t\theader_upstream Host {host}\n\t\theader_upstream X-Real-IP {remote}\n\t\theader_upstream X-Forwarded-Proto {scheme}\n\t}\n\tproxy /oidc-admin/oauth2/auth/requests PENDING {\n\t\tinsecure_skip_verify\n\t\theader_upstream Host {host}\n\t\theader_upstream X-Real-IP {remote}\n\t\theader_upstream X-Forwarded-Proto {scheme}\n\t}\n\tproxy /io   NOT_AVAILABLE {\n\t\theader_upstream Host 192.168.88.217:8082\n\t\theader_upstream X-Real-IP {remote}\n\t\theader_upstream X-Forwarded-Proto {scheme}\n\t\theader_downstream Content-Security-Policy \"script-src 'none'\"\n\t\theader_downstream X-Content-Security-Policy \"sandbox\"\n\t}\n\tproxy /data NOT_AVAILABLE {\n\t\theader_upstream Host 192.168.88.217:8082\n\t\theader_upstream X-Real-IP {remote}\n\t\theader_upstream X-Forwarded-Proto {scheme}\n\t\theader_downstream Content-Security-Policy \"script-src 'none'\"\n\t\theader_downstream X-Content-Security-Policy \"sandbox\"\n\t}\n\tproxy /ws   172.24.0.3:33731 {\n\t\twebsocket\n\t\twithout /ws\n\t}\n\tproxy /plug/ 172.24.0.3:33939 {\n\t\theader_upstream Host {host}\n\t\theader_upstream X-Real-IP {remote}\n\t\theader_upstream X-Forwarded-Proto {scheme}\n\t\theader_downstream Cache-Control \"public, max-age=31536000\"\n\t}\n\tproxy /dav PENDING {\n\t\theader_upstream Host {host}\n\t\theader_upstream X-Real-IP {remote}\n\t\theader_upstream X-Forwarded-Proto {scheme}\n\t\theader_downstream Content-Security-Policy \"script-src 'none'\"\n\t\theader_downstream X-Content-Security-Policy \"sandbox\"\n\t}\n\t\n\tproxy /public/ 172.24.0.3:33939 {\n\t\theader_upstream Host {host}\n\t\theader_upstream X-Real-IP {remote}\n\t\theader_upstream X-Forwarded-Proto {scheme}\n\t}\n\t\n\tproxy /user/reset-password/ 172.24.0.3:33939 {\n\t\theader_upstream Host {host}\n\t\theader_upstream X-Real-IP {remote}\n\t\theader_upstream X-Forwarded-Proto {scheme}\n\t}\n\t\n\tproxy /robots.txt 172.24.0.3:33939 {\n\t\theader_upstream Host {host}\n\t\theader_upstream X-Real-IP {remote}\n\t\theader_upstream X-Forwarded-Proto {scheme}\n\t}\n\t\n\tproxy /login 172.24.0.3:33939/gui {\n\t\twithout /login\n\t\theader_upstream Host {host}\n\t\theader_upstream X-Real-IP {remote}\n\t\theader_upstream X-Forwarded-Proto {scheme}\n\t}\n\n\tproxy /grpc https://PENDING {\n\t\twithout /grpc\n\t\tinsecure_skip_verify\n\t}\n\t\n\trewrite {\n\t\tif {>Content-type} has \"application/grpc\"\n\t\tto /grpc/{path}\n\t}\n\n\n\tredir 302 {\n\t\tif {>Content-type} not_has \"application/grpc\"\n\t\tif {path} is /\n\t\t/ /login\n\t}\n\t\n\t\n\t\n        proxy /wopi/ PENDING {\n            transparent\n        }\n\n        proxy /loleaflet/ https://localhost:9980/loleaflet {\n            transparent\n            insecure_skip_verify\n            without /loleaflet/\n        }\n\n        proxy /hosting/discovery https://localhost:9980/hosting/discovery {\n            transparent\n            insecure_skip_verify\n            without /hosting/discovery\n        }\n\n        proxy /lool/ https://localhost:9980/lool/ {\n            transparent\n            insecure_skip_verify\n            websocket\n            without /lool/\n        }\n    \n\t\n\t\n\trewrite {\n\t\tif {path} not_starts_with \"/a/\"\n\t\tif {path} not_starts_with \"/auth/\"\n\t\tif {path} not_starts_with \"/oidc/\"\n\t\tif {path} not_starts_with \"/oidc-admin/oauth2/auth/requests/\"\n\t\tif {path} not_starts_with \"/io\"\n\t\tif {path} not_starts_with \"/data\"\n\t\tif {path} not_starts_with \"/ws/\"\n\t\tif {path} not_starts_with \"/plug/\"\n\t\tif {path} not_starts_with \"/dav\"\n\t\t\n\t\tif {path} not_starts_with \"/wopi/\"\n\t\t\n\t\tif {path} not_starts_with \"/loleaflet/\"\n\t\t\n\t\tif {path} not_starts_with \"/hosting/discovery\"\n\t\t\n\t\tif {path} not_starts_with \"/lool/\"\n\t\t\n\t\tif {path} not_starts_with \"/public/\"\n\t\tif {path} not_starts_with \"/user/reset-password\"\n\t\tif {path} not_starts_with \"/robots.txt\"\n\t\tto {path} {path}/ /login\n\t}\n\troot /3eb80753-dc03-41eb-9e4e-7e41d0ea70e2\n\t\n\ttls \"/var/cells/certs/192.168.88.217.pem\" \"/var/cells/certs/192.168.88.217-key.pem\"\n\terrors \"/var/cells/logs/caddy_errors.log\"\n}\n\n\n\t"}
cells_1  | 2020-06-03T19:58:10.706Z     INFO    pydio.gateway.proxy     Restart done

```
Also found multiple errors in `caddy_error.log`
```
03/Jun/2020:19:59:34 +0000 [ERROR 502 /auth/dex/.well-known/openid-configuration] dial tcp: lookup PENDING on 127.0.0.11:53: no such host
```

My docker-compose file is really straightforward:
``` yaml
version: '3'

services:
    cells:
        image: pydio/cells:latest
        restart: always
        ports: ["8082:8080"]
        environment:
            - CELLS_BIND=192.168.88.217:8080
            - CELLS_EXTERNAL=https://192.168.88.217:8082
        volumes:.
            - "cellsdir:/var/cells"
            - "pics:/mnt/pictures"
            - "data:/var/cells/data"


    # MySQL image with a default database cells and a dedicated user pydio
    mysql:
         image: mariadb:latest
         restart: always
         ports: ["3306:3306"]
         environment:
             MYSQL_ROOT_PASSWORD: P@ssw0rd
             MYSQL_DATABASE: cells
             MYSQL_USER: pydio
             MYSQL_PASSWORD: P@ssw0rd
         command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
         volumes:
             - /mnt/data/config/pydio/db:/var/lib/mysql

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/data/media/pydio
      o: bind
  pics:
    driver: local
    driver_opts:
      type: none
      device: /mnt/data/media/Pictures
      o: bind

#  mysqldir: {}

  cellsdir:
    driver: local
    driver_opts:
      type: none
      device: /mnt/data/config/pydio/app
      o: bind
```
