### ISSUE TITLE
using cells docker image behind a reverse proxy

### ISSUE THREAD

**Issue by JannikStreek** [pydio/cells#4]
Hi,

i am trying to setup cells behind a reverse proxy (using nginx-proxy which controls https itself). I have already multiple apps running in this configuration but can't get cells to work. I guess the problem is that (at least from what I can see in the logs) ssl is enabled by default inside the cells docker container - and thus refusing standard connections on http 8080. 

Is there a possibility (configuration option for the docker image) to turn it off? I would like to take care of https by myself (with the reverse proxy).

docker compose part:
```
 cells:
    container_name: pydio-cells
    image: pydio/cells:latest
    restart: always
    environment:
      - VIRTUAL_HOST=pydio-cells.blabla.com
      - VIRTUAL_PORT=8080
      - CELLS_BIND=localhost:8080
    volumes:
      - /mnt/data/disk1/pydio-cells/data:/root/.config/pydio/cells/data
      - /mnt/data/disk1/pydio-cells/static:/root/.config/pydio/cells/static/pydio
```

docker image for cells: https://hub.docker.com/r/pydio/cells/
